resource/random_password+random_string: Prevent differences upgrading from 3.3.2
Reference: https://github.com/hashicorp/terraform-provider-random/issues/306

This fixes the `override_special` attribute issues by removing `Computed: true` and the empty string default value plan modifier (this attribute's value should always come from the practitioner) and resolves the underlying issue of always reading `plan.OverrideSpecial.Value` into the state, which will never be correct for null configurations.

For any environment that happened to upgrade to 3.4.2 and save the empty string into state, the replacement plan modifier will allow in-place modification from empty string (`""`) to `null`.

Previously after removing `Computed: true` and default value plan modifier:

```
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_3_2
    resource_password_test.go:221: Step 2/2 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to random_password.test, provider
        "provider[\"registry.terraform.io/hashicorp/random\"]" produced an unexpected
        new value: .override_special: was null, but now cty.StringVal("").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_4_2
    resource_password_test.go:255: Step 2/2 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to random_password.test, provider
        "provider[\"registry.terraform.io/hashicorp/random\"]" produced an unexpected
        new value: .override_special: was null, but now cty.StringVal("").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

Previously before adjusting requires replace plan modifier:

```
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_3_2
    resource_password_test.go:221: Step 2/2 error: Check failed: Check 3/3 error: attribute values are different, got :i$(*K3_Vinv and FSw{$8sB#Uc3
=== CONT  TestAccResourcePassword_OverrideSpecial_FromVersion3_4_2
    resource_password_test.go:255: Step 2/2 error: Check failed: Check 3/3 error: attribute values are different, got VrNYb]{#Z2Xu and XZD#_<BjDhkH
```